name: "mostlyai CI"

on:
  push:

jobs:
  call-lint:
    uses: ./.github/workflows/lint-check.yaml
  call-tests-cpu:
    uses: ./.github/workflows/run-tests-cpu.yaml
  call-test-gpu:
    uses: ./.github/workflows/run-tests-gpu.yaml

