name: mostlyai workflow

on:
  push:

env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
  FORCE_COLOR: "1"

jobs:
  run-lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'true'

      - name: Setup | Install Kerberos
        run: |
          sudo apt-get update
          sudo apt-get install -y krb5-user libkrb5-dev

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          python-version: '3.10'

      - name: Install dependencies
        run: uv sync --frozen --extra local-cpu

      - name: Lint | Ruff
        run: |
          uv run -- ruff check .. --ignore E741
          uv run -- ruff format --check ..

      - name: Test | End-to-End Tests
        run: |
          uv run -- pytest -vv tests/_local/end_to_end

      - name: Test | Unit Tests
        run: |
          uv run -- pytest -vv tests/client/unit
          uv run -- pytest -vv tests/_data/unit
          uv run -- pytest -vv tests/_local/unit
